### PR TITLE
Allow to build clink when msbuild is not in the `%PATH%`

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
This PR adds automatic detection of msbuild location through querying registry.

### CODE REVIEW

**Comment by mridgers** [comment]
Doing this is not so straight forward. Different versions of Visual Studio use different versions of MsBuild. The proper solution would be to check what action will be given to Premake when generating solutions and prepare the correct environment prior to calling msbuild.exe. Logic something like this;

```
# Find VisualStudio that matches intended Premake action
if not have_msbuild
  if action == vs2010 then vsenv = "vs100comntools"
  elif action == vs2012 then vsenv = "vs110comntools"
  elif action == vs2013 then vsenv = "vs120comntools"
end

# Check that the VS-provided .bat script for establishing a valid environment exists.
set_vs_env_cmd = "%vsenv%\..\..\vc\vcvarsall.bat"
if not exists(set_vs_env)
  [error]

# Run MsBuild
execute(set_vs_env + "&& msbuild.exe " ...)
```

Personally I think it's better to leave the user to be in control of their environment and not make decisions on their behalf, but that's just me.

**Comment by vladimir-kotikov** [comment]
The main goal of this change - to be able to build clink out of the box just having VS 2013 installed - no need to add MSBuild to path.

> Different versions of Visual Studio use different versions of MsBuild. 

Yup, but using default MSBuild (v4.0) works for me, even if i have a number of VS versions installed. (VS 2013 Pro + VS 2015 community, to be more precise)

To me it seems that version of MSBuild itself is not very important. What is much more important for successful build is a proper configuration of build tools (exactly what you proposing), and yes, this looks more complicated and need for testing on different configurations. Probably this can be a next step here.

I can mistake of course, pls. correct me if i'm wrong.

**Comment by mridgers** [comment]
> The main goal of this change - to be able to build clink out of the box just having VS 2013 installed - no need to add MSBuild to path.

I'm aware of that. What I'm saying is that hard coding a look up for MsBuild v4.0 is not good enough and you should instead look up Visual Studio's location have and it establish the correct environment for MsBuild to run in. Better err on the side of caution that to arbitrarily mix and match MsBuild and Visual Studio versions.

**Comment by vladimir-kotikov** [comment]
Ok, i've got it. Will rework according to your notes.

**Pull request closed without merging**
