### PR TITLE
Welcome back! 

### PR DESCRIPTION
**Pull request by Stanzilla**
Super happy to see you back @mridgers :)

Feel free to take any of these commits if you think they are useful.

### CODE REVIEW

**Comment by Stanzilla** [comment]
@mridgers well did you at least take a look?

**Comment by Peon-SouthAfrica** [comment]
Hi,

My profuse apologies for this comment here on github. Could I please ask a question not covered in the documentation?

**Comment by garoto** [comment]
[**@Peon-SouthAfrica**](https://github.com/Peon-SouthAfrica) commented on [Mar 31, 2021, 3:24 PM GMT-3](https://github.com/mridgers/clink/pull/473#issuecomment-811309171 "2021-03-31T18:24:20Z - Replied by Github Reply Comments"):
> Hi,
> 
> My profuse apologies for this comment here on github. Could I please ask a question not covered in the documentation?

Yes, this is the precise spot. Ask away.

**Comment by Peon-SouthAfrica** [comment]
I offer support services to a special needs school. In the high school lab we have a student attempting to run cmd commands with ulterior motives. Kids will be kids.

So I need to see if the student is either learning cmd in general or being naughty. However to incorporate clink I would like to remove the text detailing "Clink v0.4.9 etc" when opening cmd. If he is being naughty the student will see that and perhaps attempt other ways of naughtyness being aware of the history recording. If its innocent learning then its ok and no scene.

With full due respect I understand the copyright sign and its purpose so this might not be possible or allowed.

Thanks again, my apologies for the Github commend.

**Comment by garoto** [comment]
See here: https://github.com/mridgers/clink/issues/430

**Comment by Peon-SouthAfrica** [comment]
Thanks Garoto, not sure how I missed that.

**Pull request closed without merging**
