### PR TITLE
add support for symbolically linked readline config files

### LINKED ISSUE #461: clink doesn't read symbolically linked config files
"~/.inputrc" won't be read by **_clink_** if it's a symbolic link.

The problem is within readline.

When reading configuration files, readline tests for file size using `stat(...)`, which returns the size of the link, not the size of the target. So, the files are seen as much smaller than they are (usually 0 bytes). And, therefore, they are never read/parsed.

### PR DESCRIPTION
**Pull request by rivy**
* fixes #461

* ref/see also: <https://github.com/mridgers/clink/issues/342#issuecomment-190281005> + <https://github.com/mridgers/clink/issues/342#issuecomment-288952881>

### CODE REVIEW

**Comment by rivy** [comment]
* bump *

**Comment by rivy** [comment]
Ping @mridgers.

I've rebased this off of your current master... any interest in using it?

**Comment by garoto** [comment]
> Ping @mridgers.
> 
> I've rebased this off of your current master... any interest in using it?

He's gone mate.

**Comment by rivy** [comment]
I saw a bunch of commits back in August. I though he might have started picking back up the code.

**Comment by rivy** [comment]
* closing as stale; owner MIA

**Pull request closed without merging**
